language: python
python:
    - "2.7"

install:
  - pip install coveralls

notifications:
  email:
    recipients:
      - garykb8@gmail.com
    on_success: always
    on_failure: always

script: 
  coverage run --source=. app.py

after_success:
  coveralls